#!/bin/bash

# ==========================================================
# Weekly Unraid Backup Report Generator (Wake-on-LAN Template)
# Version: v1.0.0-wol-template
#
# Called by weekly_unraid_backup_wol_template_v1.0.0.sh after a successful
# backup while the destination server is still online.
# ==========================================================

set -o pipefail

REPORT_SCRIPT_VERSION="v1.0.0-wol-template"

META_FILE="${1:-}"
RUN_WORK_DIR="${2:-}"
REPORT_FILE="${3:-}"

if [ -z "$META_FILE" ] || [ -z "$RUN_WORK_DIR" ] || [ -z "$REPORT_FILE" ]; then
    echo "Usage: $0 META_FILE RUN_WORK_DIR REPORT_FILE"
    exit 1
fi

if [ ! -f "$META_FILE" ]; then
    echo "ERROR: Metadata file not found: $META_FILE"
    exit 1
fi

# This metadata file is generated by the paired backup script.
# shellcheck disable=SC1090
source "$META_FILE"

SHARES_PROCESSED_FILE="$RUN_WORK_DIR/shares_processed.txt"
CHANGES_DIR="$RUN_WORK_DIR/changes"
SHARE_TABLE_FILE="$RUN_WORK_DIR/share_report.tsv"

mkdir -p "$(dirname "$REPORT_FILE")"
: > "$SHARE_TABLE_FILE"

SSH_OPTS=(
    -i "$SSH_KEY"
    -o "UserKnownHostsFile=$KNOWN_HOSTS_FILE"
    -o StrictHostKeyChecking=yes
    -o UpdateHostKeys=no
    -o BatchMode=yes
)

human_bytes() {
    local BYTES="${1:-0}"

    if [ "$BYTES" = "SKIPPED" ]; then
        echo "not calculated"
        return 0
    fi

    if command -v numfmt >/dev/null 2>&1; then
        numfmt --to=iec-i --suffix=B "$BYTES" 2>/dev/null || echo "${BYTES} bytes"
        return 0
    fi

    awk -v bytes="$BYTES" '
        BEGIN {
            split("B KiB MiB GiB TiB PiB", unit, " ")
            i=1
            while (bytes >= 1024 && i < 6) {
                bytes = bytes / 1024
                i++
            }
            printf "%.2f %s\n", bytes, unit[i]
        }
    '
}

format_duration() {
    local SECONDS="${1:-0}"
    printf '%02d:%02d:%02d' \
        $((SECONDS / 3600)) \
        $(((SECONDS % 3600) / 60)) \
        $((SECONDS % 60))
}

parse_change_file() {
    local FILE="$1"

    awk -F'|' '
        $1 == "CHANGE" {
            code = $3
            bytes = $4 + 0

            # Sent regular file: newly created or updated on destination.
            if (substr(code, 1, 2) == ">f") {
                transferred_files++
                transferred_bytes += bytes
                if (code == ">f+++++++++") {
                    created_files++
                } else {
                    updated_files++
                }
            }

            # New directories are reported as cd+++++++++ by rsync.
            if (code == "cd+++++++++") {
                created_dirs++
            }

            # Symlinks and special items are counted separately.
            if (substr(code, 1, 2) == "cL" || substr(code, 1, 2) == ">L") {
                changed_links++
            }
        }
        END {
            printf "%d\t%d\t%d\t%d\t%d\t%.0f\n", \
                transferred_files + 0, created_files + 0, updated_files + 0, \
                created_dirs + 0, changed_links + 0, transferred_bytes + 0
        }
    ' "$FILE"
}

share_display_name() {
    local SHARE="$1"
    if [ "$SHARE" = "_flash_config" ]; then
        echo "flash-config (/boot/config)"
    else
        echo "$SHARE"
    fi
}

local_share_path() {
    local SHARE="$1"
    if [ "$SHARE" = "_flash_config" ]; then
        echo "/boot/config"
    else
        echo "/mnt/user/$SHARE"
    fi
}

remote_share_path() {
    local SHARE="$1"
    if [ "$SHARE" = "_flash_config" ]; then
        echo "/mnt/user/flash-backup-main-server"
    else
        echo "/mnt/user/$SHARE"
    fi
}

get_local_share_size() {
    local SHARE="$1"
    local PATH_TO_SCAN
    PATH_TO_SCAN="$(local_share_path "$SHARE")"
    du -sb -- "$PATH_TO_SCAN" 2>/dev/null | awk 'NR==1 {print $1}'
}

get_remote_share_size() {
    local SHARE="$1"
    local PATH_TO_SCAN QUOTED_PATH
    PATH_TO_SCAN="$(remote_share_path "$SHARE")"
    printf -v QUOTED_PATH '%q' "$PATH_TO_SCAN"

    ssh "${SSH_OPTS[@]}" root@"$DEST_IP" \
        "du -sb -- $QUOTED_PATH 2>/dev/null | awk 'NR==1 {print \$1}'" 2>/dev/null
}

SOURCE_DF="$(df -B1 /mnt/user 2>/dev/null | awk 'NR==2 {print $2"\t"$3"\t"$4}')"
DEST_DF="$(ssh "${SSH_OPTS[@]}" root@"$DEST_IP" "df -B1 /mnt/user 2>/dev/null | awk 'NR==2 {print \$2\"\\t\"\$3\"\\t\"\$4}'" 2>/dev/null)"

TOTAL_FILES=0
TOTAL_CREATED_FILES=0
TOTAL_UPDATED_FILES=0
TOTAL_CREATED_DIRS=0
TOTAL_CHANGED_LINKS=0
TOTAL_TRANSFER_BYTES=0
TOTAL_SOURCE_BYTES=0
TOTAL_DEST_BYTES=0

if [ ! -f "$SHARES_PROCESSED_FILE" ]; then
    echo "ERROR: Shares processed file not found: $SHARES_PROCESSED_FILE"
    exit 1
fi

while IFS= read -r SHARE; do
    [ -z "$SHARE" ] && continue

    CHANGE_FILE="$CHANGES_DIR/${SHARE}.changes"
    FILES=0
    CREATED_FILES=0
    UPDATED_FILES=0
    CREATED_DIRS=0
    CHANGED_LINKS=0
    TRANSFER_BYTES=0

    if [ -f "$CHANGE_FILE" ]; then
        IFS=$'\t' read -r FILES CREATED_FILES UPDATED_FILES CREATED_DIRS CHANGED_LINKS TRANSFER_BYTES \
            < <(parse_change_file "$CHANGE_FILE")
    fi

    if [ "${CALCULATE_SHARE_SIZES:-yes}" = "yes" ]; then
        SOURCE_BYTES="$(get_local_share_size "$SHARE")"
        DEST_BYTES="$(get_remote_share_size "$SHARE")"
        SOURCE_BYTES="${SOURCE_BYTES:-0}"
        DEST_BYTES="${DEST_BYTES:-0}"
        TOTAL_SOURCE_BYTES=$((TOTAL_SOURCE_BYTES + SOURCE_BYTES))
        TOTAL_DEST_BYTES=$((TOTAL_DEST_BYTES + DEST_BYTES))
    else
        SOURCE_BYTES="SKIPPED"
        DEST_BYTES="SKIPPED"
    fi

    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$SHARE" "$FILES" "$CREATED_FILES" "$UPDATED_FILES" "$CREATED_DIRS" \
        "$CHANGED_LINKS" "$TRANSFER_BYTES" "$SOURCE_BYTES" "$DEST_BYTES" >> "$SHARE_TABLE_FILE"

    TOTAL_FILES=$((TOTAL_FILES + FILES))
    TOTAL_CREATED_FILES=$((TOTAL_CREATED_FILES + CREATED_FILES))
    TOTAL_UPDATED_FILES=$((TOTAL_UPDATED_FILES + UPDATED_FILES))
    TOTAL_CREATED_DIRS=$((TOTAL_CREATED_DIRS + CREATED_DIRS))
    TOTAL_CHANGED_LINKS=$((TOTAL_CHANGED_LINKS + CHANGED_LINKS))
    TOTAL_TRANSFER_BYTES=$((TOTAL_TRANSFER_BYTES + TRANSFER_BYTES))
done < <(sort -u "$SHARES_PROCESSED_FILE")

DURATION_SECONDS=$((END_EPOCH - START_EPOCH))

{
    echo "======================================================================"
    echo "Weekly Unraid Backup Report"
    echo "======================================================================"
    echo "Run ID:                  $RUN_ID"
    echo "Backup script version:   $SCRIPT_VERSION"
    echo "Report script version:   $REPORT_SCRIPT_VERSION"
    echo "Mode:                    $MODE"
    echo "Status:                  SUCCESS"
    echo "Started:                 $START_TIME"
    echo "Finished:                $END_TIME"
    echo "Duration:                $(format_duration "$DURATION_SECONDS")"
    echo
    echo "Servers"
    echo "----------------------------------------------------------------------"
    echo "Main/source:             $SOURCE_IP"
    echo "Backup/destination:      $DEST_IP"
    echo "Power-on method:         ${POWER_ON_METHOD:-Wake-on-LAN}"
    echo
    echo "Backup policy"
    echo "----------------------------------------------------------------------"
    echo "Delete from backup:      NO"
    echo "Excluded share:          CCTVStorage"
    echo "Excluded report share:   BackupReports"
    echo "Excluded system images:  docker/docker.img, libvirt/libvirt.img"
    echo "Appdata excludes:        Cache/cache/tmp/temp/logs/*.sock/*.pid"
    echo "Power-on credentials:    none required for Wake-on-LAN"
    echo
    echo "Transfer totals for this run"
    echo "----------------------------------------------------------------------"
    printf 'Files transferred:       %d\n' "$TOTAL_FILES"
    printf 'New files created:       %d\n' "$TOTAL_CREATED_FILES"
    printf 'Existing files updated:  %d\n' "$TOTAL_UPDATED_FILES"
    printf 'Folders created:         %d\n' "$TOTAL_CREATED_DIRS"
    printf 'Links changed:           %d\n' "$TOTAL_CHANGED_LINKS"
    echo "Data transferred:        $(human_bytes "$TOTAL_TRANSFER_BYTES")"
    echo
    echo "Per-share transfer summary"
    echo "----------------------------------------------------------------------"
    printf '%-30s %10s %10s %10s %12s %15s\n' "Share" "Files" "New" "Updated" "Folders" "Transferred"
    printf '%-30s %10s %10s %10s %12s %15s\n' "------------------------------" "----------" "----------" "----------" "------------" "---------------"

    while IFS=$'\t' read -r SHARE FILES CREATED UPDATED DIRS LINKS BYTES SOURCE_BYTES DEST_BYTES; do
        printf '%-30s %10s %10s %10s %12s %15s\n' \
            "$(share_display_name "$SHARE")" "$FILES" "$CREATED" "$UPDATED" "$DIRS" "$(human_bytes "$BYTES")"
    done < "$SHARE_TABLE_FILE"

    echo
    echo "Current storage footprint after backup"
    echo "----------------------------------------------------------------------"
    echo "Destination sizes can be larger because no-delete retains files that"
    echo "are no longer present on the main server. Size scans may add runtime."
    echo

    if [ "${CALCULATE_SHARE_SIZES:-yes}" = "yes" ]; then
        printf '%-30s %18s %18s\n' "Share" "Main size" "Backup size"
        printf '%-30s %18s %18s\n' "------------------------------" "------------------" "------------------"

        while IFS=$'\t' read -r SHARE FILES CREATED UPDATED DIRS LINKS BYTES SOURCE_BYTES DEST_BYTES; do
            printf '%-30s %18s %18s\n' \
                "$(share_display_name "$SHARE")" "$(human_bytes "$SOURCE_BYTES")" "$(human_bytes "$DEST_BYTES")"
        done < "$SHARE_TABLE_FILE"

        echo
        printf '%-30s %18s %18s\n' "TOTAL PROCESSED PATHS" \
            "$(human_bytes "$TOTAL_SOURCE_BYTES")" "$(human_bytes "$TOTAL_DEST_BYTES")"
    else
        echo "Per-share size scan disabled in backup script configuration."
    fi

    echo
    echo "Filesystem capacity"
    echo "----------------------------------------------------------------------"

    if [ -n "$SOURCE_DF" ]; then
        IFS=$'\t' read -r FS_TOTAL FS_USED FS_FREE <<< "$SOURCE_DF"
        echo "Main /mnt/user total:    $(human_bytes "$FS_TOTAL")"
        echo "Main /mnt/user used:     $(human_bytes "$FS_USED")"
        echo "Main /mnt/user free:     $(human_bytes "$FS_FREE")"
    else
        echo "Main /mnt/user capacity: unavailable"
    fi

    if [ -n "$DEST_DF" ]; then
        IFS=$'\t' read -r FS_TOTAL FS_USED FS_FREE <<< "$DEST_DF"
        echo "Backup /mnt/user total:  $(human_bytes "$FS_TOTAL")"
        echo "Backup /mnt/user used:   $(human_bytes "$FS_USED")"
        echo "Backup /mnt/user free:   $(human_bytes "$FS_FREE")"
    else
        echo "Backup /mnt/user capacity: unavailable"
    fi

    echo
    echo "Notes"
    echo "----------------------------------------------------------------------"
    echo "- Files present only on the backup server are retained."
    echo "- Existing destination files are overwritten when the main copy changes."
    echo "- Transfer totals describe this run only; footprint describes current data."
    echo "======================================================================"
} | tee "$REPORT_FILE"

exit 0
